### ISSUE TITLE
Check localhost instead of my defined hostname

### ISSUE THREAD

**Issue by PayamVA** [microsoft/WAFBench#40]
Hi folks,

I used the example you made for the docker:

`docker run -ti --rm -v `pwd`:/data --rm wafbench ftw_compatible_tool -d /data/regression.db -x "load util/regression-test/crs-v3.1/black-box/ | gen | start hostname:port| report | exit"`

I changed `hostname:port` to `www.mywebsite.com:443` or `www.mywebsite.com:80` but it still check my localhost ( I guess the default value from the regression-test)!

Examples:

`docker run -ti --rm -v `pwd`:/data --rm wafbench ftw_compatible_tool -d /data/regression.db -x "load util/regression-test/crs-v3.1/black-box/ | gen | start www.mywebsite.com:443| report | exit"`

OR

`docker run -ti --rm -v `pwd`:/data --rm wafbench ftw_compatible_tool -d /data/regression.db -x "load util/regression-test/crs-v3.1/black-box/ | gen | start www.mywebsite.com:80| report | exit"`

Can you please advise what should be done?

Note: I fixed the issue by changing the original files in WAFBench/util/regression-test, I converted all `dest_addr` and `port` to my host name and port number.

**Comment by Pterosaur** [comment]
Hi Payam,

Sorry for too late response. 
Yes, you are right, the `hostname:localhost` and `port:80` were hard coded into the regression-test. Because if the target machine was behind a proxy and we cannot know what is the real `hostname`. We also need to modify the original files in regression-test in our scenario.
We provided a sample script, https://github.com/microsoft/WAFBench/blob/master/tools/hostname_port_modifier.sh, to do what you want.

But thanks for your issue, I will polish our Readme to make it clearer.
